# https://probot.github.io/apps/settings/

repository:
  description: ü´ê The DjangoCon US 2023 conference website
  homepage: https://2023.djangocon.us
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

collaborators:
  # Note: Only valid on organization-owned repositories.
  # The permission to grant the collaborator. Can be one of:
  # * `pull` - can pull, but not push to or administer this repository.
  # * `push` - can pull and push, but not administer this repository.
  # * `admin` - can pull, push and administer this repository.
  - username: drewbrew
    permission: admin
  - username: adamfast
    permission: admin
  - username: emmakodes
    permission: push
